baseurl = "https://wiki.evos.live/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "evos.live"
canonifyurls  = true
enableRobotsTXT=true

DefaultContentLanguage = "en"
theme = "hugo-theme-relearn"

enableGitInfo = true
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

#####################################
#Allows for using html in markdown to do colored text etc.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
#####################################
[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'
[Params]
  subtitle = "Wiki containing info from things at evos.live"
  logo = "img/avatar-icon.png"
  favicon = "assets/images/favicon.png"
  commit = true
  rss = true
  comments = false
  disableNextPrev = false
  ordersectionsby = "weight"
  editURL = "https://github.com/Addalyn/addalyn.github.io/tree/main/content/"
  disableLandingPageButton = true
  titleSeparator = "|"
  collapsibleMenu = true
  themeVariant = [
	{ identifier = "zen-auto",      name = "Zen Light/Dark", auto = [ "zen-light", "zen-dark" ] },
]
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[outputs]
home = [ "HTML", "RSS", "JSON"]